/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator.by.gab;

import javax.swing.ImageIcon;

  
public class CalcuLatorByGaby extends javax.swing.JFrame {

   double firstnum;
   double secondnum;
   double result;
   String operations;
    public CalcuLatorByGaby() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/cacl.png"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxt = new javax.swing.JTextField();
        key2 = new javax.swing.JButton();
        key1 = new javax.swing.JButton();
        key3 = new javax.swing.JButton();
        key4 = new javax.swing.JButton();
        key5 = new javax.swing.JButton();
        key6 = new javax.swing.JButton();
        key7 = new javax.swing.JButton();
        key8 = new javax.swing.JButton();
        key9 = new javax.swing.JButton();
        key10 = new javax.swing.JButton();
        key11 = new javax.swing.JButton();
        key12 = new javax.swing.JButton();
        key13 = new javax.swing.JButton();
        key14 = new javax.swing.JButton();
        key15 = new javax.swing.JButton();
        key16 = new javax.swing.JButton();
        key17 = new javax.swing.JButton();
        key18 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalculatorByGab");
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jtxt.setBackground(new java.awt.Color(153, 153, 153));
        jtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxt.setBorder(null);
        jtxt.setSelectionColor(new java.awt.Color(51, 51, 51));
        jtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtActionPerformed(evt);
            }
        });

        key2.setBackground(new java.awt.Color(187, 206, 228));
        key2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key2.setText("2");
        key2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key2ActionPerformed(evt);
            }
        });

        key1.setBackground(new java.awt.Color(187, 206, 228));
        key1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key1.setText("1");
        key1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key1ActionPerformed(evt);
            }
        });

        key3.setBackground(new java.awt.Color(187, 206, 228));
        key3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key3.setText("3");
        key3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key3ActionPerformed(evt);
            }
        });

        key4.setBackground(new java.awt.Color(187, 206, 228));
        key4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key4.setText("4");
        key4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key4ActionPerformed(evt);
            }
        });

        key5.setBackground(new java.awt.Color(187, 206, 228));
        key5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key5.setText("5");
        key5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key5ActionPerformed(evt);
            }
        });

        key6.setBackground(new java.awt.Color(187, 206, 228));
        key6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key6.setText("6");
        key6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key6ActionPerformed(evt);
            }
        });

        key7.setBackground(new java.awt.Color(187, 206, 228));
        key7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key7.setText("7");
        key7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key7ActionPerformed(evt);
            }
        });

        key8.setBackground(new java.awt.Color(187, 206, 228));
        key8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key8.setText("8");
        key8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key8ActionPerformed(evt);
            }
        });

        key9.setBackground(new java.awt.Color(187, 206, 228));
        key9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key9.setText("9");
        key9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key9ActionPerformed(evt);
            }
        });

        key10.setBackground(new java.awt.Color(187, 206, 228));
        key10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key10.setText("0");
        key10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key10ActionPerformed(evt);
            }
        });

        key11.setBackground(new java.awt.Color(255, 51, 0));
        key11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key11.setText("+");
        key11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key11ActionPerformed(evt);
            }
        });

        key12.setBackground(new java.awt.Color(255, 51, 0));
        key12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key12.setText("-");
        key12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key12ActionPerformed(evt);
            }
        });

        key13.setBackground(new java.awt.Color(255, 51, 0));
        key13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key13.setText("/");
        key13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key13ActionPerformed(evt);
            }
        });

        key14.setBackground(new java.awt.Color(255, 51, 0));
        key14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key14.setText("*");
        key14.setToolTipText("");
        key14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key14ActionPerformed(evt);
            }
        });

        key15.setBackground(new java.awt.Color(255, 0, 0));
        key15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key15.setText("C");
        key15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key15ActionPerformed(evt);
            }
        });

        key16.setBackground(new java.awt.Color(255, 51, 0));
        key16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key16.setText("-/+");
        key16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key16ActionPerformed(evt);
            }
        });

        key17.setBackground(new java.awt.Color(255, 51, 0));
        key17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key17.setText(".");
        key17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key17ActionPerformed(evt);
            }
        });

        key18.setBackground(new java.awt.Color(255, 0, 0));
        key18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        key18.setText("=");
        key18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        key18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key18ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("KAKSIO");

        label2.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("By: Gab");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(key15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(key18, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(key13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(key14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(key9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(key10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(key1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(key2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(key5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(key6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(key7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(key8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(key3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(key4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(key11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(key12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(key16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(key17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key17, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key18, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtActionPerformed
       
    }//GEN-LAST:event_jtxtActionPerformed

    private void key1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key1ActionPerformed
        String Enternumber = jtxt.getText()+ key1.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key1ActionPerformed

    private void key2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key2ActionPerformed
      String Enternumber = jtxt.getText()+ key2.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key2ActionPerformed

    private void key3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key3ActionPerformed
        String Enternumber = jtxt.getText()+ key3.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key3ActionPerformed

    private void key4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key4ActionPerformed
       String Enternumber = jtxt.getText()+ key4.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key4ActionPerformed

    private void key5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key5ActionPerformed
       String Enternumber = jtxt.getText()+ key5.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key5ActionPerformed

    private void key6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key6ActionPerformed
        String Enternumber = jtxt.getText()+ key6.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key6ActionPerformed

    private void key7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key7ActionPerformed
        String Enternumber = jtxt.getText()+ key7.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key7ActionPerformed

    private void key8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key8ActionPerformed
        String Enternumber = jtxt.getText()+ key8.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key8ActionPerformed

    private void key9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key9ActionPerformed
        String Enternumber = jtxt.getText()+ key9.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key9ActionPerformed

    private void key10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key10ActionPerformed
       String Enternumber = jtxt.getText()+ key10.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_key10ActionPerformed

    private void key15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key15ActionPerformed
       jtxt.setText(" ");
    }//GEN-LAST:event_key15ActionPerformed

    private void key14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key14ActionPerformed
       firstnum = Double.parseDouble(jtxt.getText());
       jtxt.setText("");
       operations="*"; 
    }//GEN-LAST:event_key14ActionPerformed

    private void key11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key11ActionPerformed
        firstnum = Double.parseDouble(jtxt.getText());
       jtxt.setText("");
       operations="+"; 
    }//GEN-LAST:event_key11ActionPerformed

    private void key12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key12ActionPerformed
       firstnum = Double.parseDouble(jtxt.getText());
       jtxt.setText("");
       operations="-"; 
    }//GEN-LAST:event_key12ActionPerformed

    private void key13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key13ActionPerformed
      firstnum = Double.parseDouble(jtxt.getText());
       jtxt.setText("");
       operations="/"; 
    }//GEN-LAST:event_key13ActionPerformed

    private void key18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key18ActionPerformed
       String answer;
        secondnum = Double.parseDouble(jtxt.getText());
        if(operations == "+"){
            result = firstnum + secondnum;
            answer = String.format("%.0f", result);
            jtxt.setText(answer);
        }
        else if(operations == "-"){
            result = firstnum - secondnum;
            answer = String.format("%.0f", result);
            jtxt.setText(answer);
        }
         else if(operations == "/"){
            result = firstnum / secondnum;
            answer = String.format("%.0f", result);
            jtxt.setText(answer);
        }
         else if(operations == "*"){
            result = firstnum * secondnum;
            answer = String.format("%.0f", result);
            jtxt.setText(answer);
        }
         else if(operations == "%"){
            result = firstnum % secondnum;
            answer = String.format("%.0f", result);
            jtxt.setText(answer);
        }
    }//GEN-LAST:event_key18ActionPerformed

    private void key17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key17ActionPerformed
       String Enternumber = jtxt.getText()+ key10.getText();
        jtxt.setText(".");
    }//GEN-LAST:event_key17ActionPerformed

    private void key16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key16ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxt.getText()));
        ops = ops * (-1);
        jtxt.setText(String.valueOf(ops));
    }//GEN-LAST:event_key16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcuLatorByGaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcuLatorByGaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcuLatorByGaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcuLatorByGaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcuLatorByGaby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxt;
    private javax.swing.JButton key1;
    private javax.swing.JButton key10;
    private javax.swing.JButton key11;
    private javax.swing.JButton key12;
    private javax.swing.JButton key13;
    private javax.swing.JButton key14;
    private javax.swing.JButton key15;
    private javax.swing.JButton key16;
    private javax.swing.JButton key17;
    private javax.swing.JButton key18;
    private javax.swing.JButton key2;
    private javax.swing.JButton key3;
    private javax.swing.JButton key4;
    private javax.swing.JButton key5;
    private javax.swing.JButton key6;
    private javax.swing.JButton key7;
    private javax.swing.JButton key8;
    private javax.swing.JButton key9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
